apiVersion: v1
kind: Service
metadata:
  name: mysql  # Simulates the 'db' hostname from docker-compose
  labels:
    app: {{ .Release.Name }}-db
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: {{ .Release.Name }}-db
  clusterIP: None # Headless service for StatefulSet
